// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
	site: 'https://docs.stackblaze.com',
	redirects: {
		'/databases/overview': '/databases',
		'/docs': '/',
		'/docs/[...slug]': '/[...slug]',
	},
	integrations: [
		starlight({
			title: 'StackBlaze Docs',
			description:
				'Deploy services, databases, and jobs on StackBlaze from a project canvas.',
			favicon: '/favicon.svg',
			logo: {
				src: './src/assets/logo.svg',
				alt: 'StackBlaze',
			},
			customCss: ['./src/styles/custom.css'],
			editLink: {
				baseUrl: 'https://github.com/stackblaze/docs/edit/main/',
			},
			components: {
				SiteTitle: './src/components/SiteTitle.astro',
				SocialIcons: './src/components/SocialIcons.astro',
			},
			sidebar: [
				{ slug: 'quickstart', label: 'Quick start' },
				{ slug: 'concepts', label: 'The basics' },
				{ slug: 'agents', label: 'StackBlaze for Agents' },
				{ slug: 'overview/best-practices', label: 'Best practices' },
				{ slug: 'overview/advanced-concepts', label: 'Advanced concepts' },
				{
					slug: 'overview/production-readiness',
					label: 'Production readiness checklist',
				},
				{ slug: 'guides', label: 'Guides' },
				{ slug: 'overview/keyboard-shortcuts', label: 'Keyboard shortcuts' },
				{
					label: 'Platform',
					collapsed: true,
					items: [
						{ slug: 'platform', label: 'Overview' },
						{ slug: 'platform/philosophy', label: 'Philosophy' },
						{ slug: 'platform/use-cases', label: 'Use cases' },
						{ slug: 'platform/support', label: 'Support' },
						{
							label: 'Compare to StackBlaze',
							items: [
								{ label: 'Compare to Heroku', link: 'https://stackblaze.com/compare/heroku' },
								{ label: 'Compare to Render', link: 'https://stackblaze.com/compare/render' },
								{ label: 'Compare to Fly.io', link: 'https://stackblaze.com/compare/fly-io' },
								{ label: 'Compare to Railway', link: 'https://stackblaze.com/compare/railway' },
								{ label: 'Compare to Vercel', link: 'https://stackblaze.com/compare/vercel' },
							],
						},
						{
							label: 'Migrate to StackBlaze',
							items: [{ slug: 'platform/migrate-from-heroku', label: 'Migrate from Heroku' }],
						},
					],
				},
				{
					label: 'Pricing',
					collapsed: true,
					items: [
						{ slug: 'reference/pricing', label: 'Plans' },
						{ slug: 'reference/limits', label: 'Limits' },
					],
				},
				{
					label: 'Enterprise',
					collapsed: true,
					items: [
						{ slug: 'enterprise', label: 'Overview' },
						{ slug: 'enterprise/saml', label: 'SAML SSO' },
						{ slug: 'security/two-factor-auth', label: 'Two-factor enforcement' },
						{ slug: 'security/team-permissions', label: 'Access groups' },
						{ slug: 'security/ip-allowlist', label: 'IP allowlisting' },
						{ slug: 'enterprise/audit-logs', label: 'Audit logs' },
					],
				},
				{
					label: 'AI',
					collapsed: true,
					items: [
						{ slug: 'ai', label: 'Overview' },
						{ slug: 'agents', label: 'StackBlaze Agent' },
						{ slug: 'ai/connectors', label: 'Agent connectors' },
						{ slug: 'ai/mcp', label: 'MCP server' },
						{ slug: 'cli/agent', label: 'CLI agent' },
						{ slug: 'cli/skills', label: 'Agent skills' },
					],
				},
				{
					label: 'Templates & open source',
					collapsed: true,
					items: [
						{ slug: 'templates', label: 'Deploy' },
						{ slug: 'templates/create', label: 'Create' },
					],
				},
				{
					label: 'Languages & frameworks',
					collapsed: true,
					items: [
						{ slug: 'languages-frameworks', label: 'Overview' },
						{
							label: 'JavaScript / TypeScript',
							items: [
								{ slug: 'guides/nextjs', label: 'Next.js' },
								{ slug: 'guides/express', label: 'Express' },
								{ slug: 'guides/hono', label: 'Hono' },
								{ slug: 'guides/fastify', label: 'Fastify' },
								{ slug: 'guides/nestjs', label: 'Nest.js' },
								{ slug: 'guides/remix', label: 'Remix' },
								{ slug: 'guides/nuxt', label: 'Nuxt' },
								{ slug: 'guides/astro', label: 'Astro' },
								{ slug: 'guides/sveltekit', label: 'SvelteKit' },
								{ slug: 'guides/bun', label: 'Bun' },
								{ slug: 'guides/react', label: 'React' },
								{ slug: 'guides/vue', label: 'Vue' },
								{ slug: 'guides/angular', label: 'Angular' },
								{ slug: 'guides/solid', label: 'Solid' },
								{ slug: 'guides/sails', label: 'Sails' },
								{ slug: 'guides/gatsby', label: 'Gatsby' },
								{ slug: 'guides/tanstack-start', label: 'TanStack Start' },
							],
						},
						{
							label: 'Python',
							items: [
								{ slug: 'guides/fastapi', label: 'FastAPI' },
								{ slug: 'guides/flask', label: 'Flask' },
								{ slug: 'guides/django', label: 'Django' },
							],
						},
						{
							label: 'PHP',
							items: [
								{ slug: 'guides/laravel', label: 'Laravel' },
								{ slug: 'guides/symfony', label: 'Symfony' },
							],
						},
						{
							label: 'Ruby',
							items: [{ slug: 'guides/rails', label: 'Rails' }],
						},
						{
							label: 'Go',
							items: [
								{ slug: 'guides/gin', label: 'Gin' },
								{ slug: 'guides/go-fiber', label: 'Go Fiber' },
								{ slug: 'guides/beego', label: 'Beego' },
							],
						},
						{
							label: 'Rust',
							items: [
								{ slug: 'guides/axum', label: 'Axum' },
								{ slug: 'guides/actix-web', label: 'Actix Web' },
								{ slug: 'guides/rocket', label: 'Rocket' },
							],
						},
						{
							label: 'Java',
							items: [{ slug: 'guides/spring-boot', label: 'Spring Boot' }],
						},
						{
							label: 'Kotlin',
							items: [{ slug: 'guides/ktor', label: 'Ktor' }],
						},
						{
							label: 'C#',
							items: [{ slug: 'guides/aspnet-core', label: 'ASP.NET Core' }],
						},
						{
							label: 'Scala',
							items: [{ slug: 'guides/play', label: 'Play' }],
						},
						{
							label: 'Elixir',
							items: [
								{ slug: 'guides/phoenix', label: 'Phoenix' },
								{ slug: 'guides/phoenix-distillery', label: 'Phoenix + Distillery' },
							],
						},
						{
							label: 'Clojure',
							items: [{ slug: 'guides/luminus', label: 'Luminus' }],
						},
					],
				},
				{
					label: 'CLI',
					collapsed: true,
					items: [
						{ slug: 'cli', label: 'Overview' },
						{ slug: 'cli/login', label: 'login' },
						{ slug: 'cli/logout', label: 'logout' },
						{ slug: 'cli/whoami', label: 'whoami' },
						{ slug: 'cli/init', label: 'init' },
						{ slug: 'cli/link', label: 'link' },
						{ slug: 'cli/unlink', label: 'unlink' },
						{ slug: 'cli/up', label: 'up' },
						{ slug: 'cli/down', label: 'down' },
						{ slug: 'cli/status', label: 'status' },
						{ slug: 'cli/open', label: 'open' },
						{ slug: 'cli/logs', label: 'logs' },
						{ slug: 'cli/metrics', label: 'metrics' },
						{ slug: 'cli/run', label: 'run' },
						{ slug: 'cli/shell', label: 'shell' },
						{ slug: 'cli/ssh', label: 'ssh' },
						{ slug: 'cli/connect', label: 'connect' },
						{ slug: 'cli/variables', label: 'variables' },
						{ slug: 'cli/env', label: 'env' },
						{ slug: 'cli/apps', label: 'apps' },
						{ slug: 'cli/pipelines', label: 'pipelines' },
						{ slug: 'cli/phases', label: 'phases' },
						{ slug: 'cli/builds', label: 'builds' },
						{ slug: 'cli/deployments', label: 'deployments' },
						{ slug: 'cli/domain', label: 'domain' },
						{ slug: 'cli/templates', label: 'templates' },
						{ slug: 'cli/addons', label: 'addons' },
						{ slug: 'cli/functions', label: 'functions' },
						{ slug: 'cli/waf', label: 'waf' },
						{ slug: 'cli/volume', label: 'volume' },
						{ slug: 'cli/snapshots', label: 'snapshots' },
						{ slug: 'cli/files', label: 'files' },
						{ slug: 'cli/apply', label: 'apply' },
						{ slug: 'cli/plan', label: 'plan' },
						{ slug: 'cli/export', label: 'export' },
						{ slug: 'cli/destroy', label: 'destroy' },
						{ slug: 'cli/agent', label: 'agent' },
						{ slug: 'cli/mcp', label: 'mcp' },
						{ slug: 'cli/skills', label: 'skills' },
						{ slug: 'cli/setup', label: 'setup' },
						{ slug: 'cli/completion', label: 'completion' },
						{ slug: 'cli/upgrade', label: 'upgrade' },
						{ slug: 'cli/docs', label: 'docs' },
						{ slug: 'cli/billing', label: 'billing' },
						{ slug: 'cli/audit', label: 'audit' },
						{ slug: 'cli/diagnose', label: 'diagnose' },
						{ slug: 'cli/inspect', label: 'inspect' },
						{ slug: 'cli/wait', label: 'wait' },
						{ slug: 'cli/scale', label: 'scale' },
						{ slug: 'cli/restart', label: 'restart' },
						{ slug: 'cli/redeploy', label: 'redeploy' },
						{ slug: 'cli/list', label: 'list' },
						{ slug: 'cli/context', label: 'context' },
					],
				},
				{
					label: 'Projects',
					collapsed: true,
					items: [
						{ slug: 'projects', label: 'Overview' },
						{ slug: 'security/team-permissions', label: 'Project members' },
						{ slug: 'reference/limits', label: 'Project usage' },
					],
				},
				{
					label: 'Build & deploy',
					collapsed: true,
					items: [
						{ slug: 'build-deploy', label: 'Overview' },
						{ slug: 'build-deploy/apps', label: 'Services' },
						{ slug: 'deploy/environments', label: 'Environments' },
						{ slug: 'security/env-vars', label: 'Variables' },
						{ slug: 'deploy/cron-jobs', label: 'Cron jobs' },
						{ slug: 'functions', label: 'Functions' },
						{ slug: 'blueprint', label: 'Config as code' },
						{
							label: 'Builds',
							items: [
								{ slug: 'deploy/github', label: 'GitHub' },
								{ slug: 'deploy/docker', label: 'Dockerfiles' },
								{ slug: 'cicd/monorepo', label: 'Monorepo' },
							],
						},
						{
							label: 'Deployments',
							items: [
								{ slug: 'cicd/auto-deploy', label: 'GitHub autodeploys' },
								{ slug: 'cicd/pr-previews', label: 'PR previews' },
								{ slug: 'cicd/deploy-hooks', label: 'Deploy hooks' },
								{ slug: 'cicd/rollbacks', label: 'Rollbacks' },
								{ slug: 'deploy/staged-changes', label: 'Staged changes' },
								{ slug: 'storage/health-checks', label: 'Healthchecks' },
								{ slug: 'scaling/horizontal', label: 'Scaling' },
								{ slug: 'scaling/autoscaling', label: 'Autoscaling' },
								{ slug: 'scaling/zero-downtime', label: 'Zero downtime' },
								{ slug: 'scaling/limits', label: 'Resources' },
								{ slug: 'deploy/web-services', label: 'Public HTTP' },
								{ slug: 'deploy/background-workers', label: 'Private services' },
								{ slug: 'deploy/static-sites', label: 'Static sites' },
								{ slug: 'deploy/docker-compose', label: 'Import' },
							],
						},
					],
				},
				{
					label: 'Data & storage',
					collapsed: true,
					items: [
						{ slug: 'data-storage', label: 'Overview' },
						{
							label: 'Databases',
							items: [
								{ slug: 'databases', label: 'All databases' },
								{ slug: 'databases/postgresql', label: 'PostgreSQL' },
								{ slug: 'databases/mysql', label: 'MySQL' },
								{ slug: 'databases/redis', label: 'Redis' },
								{ slug: 'databases/mongodb', label: 'MongoDB' },
								{ slug: 'databases/cockroachdb', label: 'CockroachDB' },
								{ slug: 'databases/clickhouse', label: 'ClickHouse' },
								{ slug: 'databases/opensearch', label: 'OpenSearch' },
								{ slug: 'databases/milvus', label: 'Milvus' },
								{ slug: 'databases/cassandra', label: 'Cassandra' },
								{ slug: 'databases/scylladb', label: 'ScyllaDB' },
								{ slug: 'databases/couchdb', label: 'CouchDB' },
								{ slug: 'databases/memcached', label: 'Memcached' },
								{ slug: 'messaging/kafka', label: 'Kafka' },
								{ slug: 'messaging/rabbitmq', label: 'RabbitMQ' },
							],
						},
						{
							label: 'Volumes',
							items: [
								{ slug: 'storage/persistent-disks', label: 'Volumes' },
								{ slug: 'databases/backups', label: 'Backups' },
								{ slug: 'databases/pitr', label: 'Point-in-time recovery' },
							],
						},
					],
				},
				{
					label: 'Networking',
					collapsed: true,
					items: [
						{ slug: 'networking', label: 'Overview' },
						{ slug: 'networking/custom-domains', label: 'Public networking' },
						{ slug: 'networking/private-networking', label: 'Private networking' },
						{ slug: 'networking/ssl', label: 'SSL' },
						{ slug: 'networking/websockets', label: 'WebSockets' },
						{ slug: 'networking/redirects', label: 'Redirects' },
						{ slug: 'networking/waf', label: 'WAF' },
					],
				},
				{
					label: 'Observability',
					collapsed: true,
					items: [
						{ slug: 'observability', label: 'Overview' },
						{ slug: 'observability/logs', label: 'Logs' },
						{ slug: 'observability/metrics', label: 'Metrics' },
						{ slug: 'operations/observability', label: 'Coroot' },
						{ slug: 'operations/troubleshooting', label: 'Troubleshooting' },
					],
				},
				{
					label: 'Access',
					collapsed: true,
					items: [
						{ slug: 'access', label: 'Accounts' },
						{ slug: 'security/two-factor-auth', label: 'Multi-factor authentication' },
						{ slug: 'security/secret-files', label: 'Secret files' },
						{ slug: 'security/ip-allowlist', label: 'IP allowlisting' },
					],
				},
				{
					label: 'Integrations',
					collapsed: true,
					items: [
						{ slug: 'integrations', label: 'Overview' },
						{ slug: 'reference/api', label: 'API' },
						{ slug: 'ai/mcp', label: 'MCP' },
						{ slug: 'deploy/github', label: 'GitHub' },
					],
				},
			],
		}),
	],
});
